### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Fastidious** [jung-kurt/caddy-cgi#1]
How to use this plugin? Is there a compiled version somewhere? I could not find it on the Caddy server build page, so I am not sure how can it be used. Thanks!

**Comment by jung-kurt** [comment]
You'll either need to wait for the next versioned release of Caddy, or build it from source. In the latter case, you'll need to 

* import "github.com/jung-kurt/caddy-cgi" into caddyhttp/caddyhttp.go
* add "cgi" after "fastcgi" in the directives slice in caddyhttp/httpserver/plugin.go

Good luck!

**Comment by Fastidious** [comment]
@jung-kurt thanks for the reply. I will wait for the next versioned release, not in a rush. Cheers!
