### ISSUE TITLE
Is it compatible with Windows 7 x64 to run cgi scripts?

### ISSUE THREAD

**Issue by magikstm** [jung-kurt/caddy-cgi#2]
There are a few packages of Perl available.

I visited: https://www.perl.org/get.html

I tried installing:
- ActiveState Perl
- Strawberry Perl

I adjusted the first line of my cgi to the perl exe. I got 500 errors in Caddy.

Is it compatible with Windows 7 x64?

Is there a documentation detailing steps required for it to work with a tested package?

**Comment by jung-kurt** [comment]
> Is it compatible with Windows 7 x64?

Yes, the CGI plugin should work wherever Caddy works. However, the [documentation](https://jung-kurt.github.io/cgi/) is admittedly sparse when it comes to Windows. I will be able to remedy this in the next couple of weeks when I get access to a Windows machine.

I think, but can't verify, that something like this should work. Let's say your perl executable is `c:\perl\perl.exe` and that you have a file named `c:\perl\hello.pl` that looks like this:

    print "Content-type: text/plain\n\n";
    print "Hello, world!\n";

Then the Caddy directive could look like this:

    cgi /hello c:\perl\perl.exe c:\perl\hello.pl

If that doesn't work, try changing the backslashes to forward slashes.

**Comment by magikstm** [comment]
Thanks a lot.

It worked with "Strawberry Perl 5.26.0.1 (64bit)" available here:
http://strawberryperl.com/

I was missing that part in the cgi line:
c:\perl\perl.exe

Which on a default strawberry install is:
C:\Strawberry\perl\bin\perl.exe

I didn't have to do anything else for it to work for my first 3 small cgi scripts (hello world, cgi version test and a small whereami script).

This worked:
```
#!/usr/bin/perl -w
print "Content-type: text/html\n\n"; # This is mandatory.
print "<h2>Hello world!</h2>";
```

This also worked:
```
#!/usr/bin/perl -w
# test.cgi by Bill Weinman [http://bw.org/]
# Copyright 1995-2008 The BearHeart Group, LLC
# Free Software: Use and distribution under the same terms as perl.

use strict;
use warnings;
use CGI;

print foreach (
    "Content-Type: text/plain\n\n",
    "BW Test version 5.0\n",
    "Copyright 1995-2008 The BearHeart Group, LLC\n\n",
    "Versions:\n=================\n",
    "perl: $]\n",
    "CGI: $CGI::VERSION\n"
);
```

**Comment by jung-kurt** [comment]
Thanks for the update, @magikstm.

On Unix systems, that shebang line (`#!/usr/bin/perl -w`) is sufficient to make the script itself executable. But on Windows it looks like it's best to identify the perl executable with the script name as an argument.

Incidentally, the `-w` switch activates warnings, something you may want to do. In that case, you would use the directive 

    cgi /hello C:\Strawberry\perl\bin\perl.exe -w C:\path\to\hello.pl
